[package]
name = "uptechstar-rs"
version = "0.1.0"
edition = "2024"

authors = ["Whth <88489697+Whth@users.noreply.github.com>"]



[dependencies]
libloading = "0.8.8"
log = "0.4.27"
once_cell = "1.21.3"
tempfile = "3.20.0"


