name: Publish Crate

on:
  push:
    branches:
      - master
    # Trigger the workflow when Cargo.toml changes (specifically version changes)
    paths:
      - 'Cargo.toml'
      - 'src/**/*'
  pull_request:

    branches:
      - master
    paths:
      - 'Cargo.toml'
      - 'src/**/*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build documentation
        run: cargo doc --no-deps

      - name: Run tests
        run: cargo test

      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}